---
# tasks file for supercollider

- name: install supercollider 
  apt:
    name: supercollider
    state: latest

- name: install jackd
  apt:
    name: jackd
    state: latest

- name: template asound.conf
  template:
    src: asound.conf.j2
    dest: /etc/asound.conf

- name: template start script
  template:
    src: launch.sh.j2
    dest: /usr/sbin/launch_supercollider.sh
    mode: '0770'

- name: template sc service
  template:
    src: sc.service.j2
    dest: /etc/systemd/system/sc.service

- name: enable and start sc srvice
  systemd:
    daemon-reload: true
    name: sc.service
    state: started
    enabled: true

- name: create working dir
  file:
    path: /var/opt/sc/
    state: directory

- name: template demo file
  template:
    src: demo.scd.j2
    dest: /var/opt/sc/demo.scd

- name: link demo file
  file:
    state: link
    dest: /var/opt/sc/project.scd
    src: /var/opt/sc/demo.scd 
